server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com
  #    hostname: microservicecloud-eureka-7003
  client:
    # 下面两个配置就是强调此服务为注册中心服务，不负责将本服务注册或者发现本服务
    register-with-eureka: false
    fetch-registry: false
    # 设置与Eureka Server交互的地址 查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 单机情况
