spring:
  application:
    name: mircoservicecloud-config
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/txlovetue/microservicecloud-config.git
          uri: git@github.com:txlovetue/microservicecloud-config.git  # GitHub远程仓库地址
server:
  port: 3344


